name: escom_app
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.5.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Firebase dependencies compatibles
  firebase_core: ^3.8.0
  firebase_auth: 5.3.3
  cloud_firestore: ^5.3.3
  flutter_map: ^7.0.2
  latlong2: ^0.9.1
  geocoding: ^2.0.0
  open_route_service: ^1.2.6
  geolocator: ^9.0.0
  location: ^7.0.1
  http: ^1.2.2
  permission_handler: ^11.3.1
  provider: ^6.1.0
  carousel_slider: ^5.0.0
  image_picker: ^0.8.7+4
  path_provider: ^2.0.13
  flutter_pdfview: ^1.4.0
  table_calendar: ^3.0.8
  #flutter_webview_plugin: ^0.4.0
  url_launcher: ^6.1.10
  ikchatbot: ^1.0.2
  shared_preferences: ^2.1.0
  #webview_flutter: ^4.0.5

  # Dependencia para íconos estilo iOS
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Bold.ttf

  # Agrega tu imagen
  assets:
    - assets/img/ajedrez.jpg
    - assets/img/aniversario.jpg
    - assets/img/arcoiris.jpg
    - assets/img/atardecer.jpg
    - assets/img/auditorio.jpg
    - assets/img/baile.jpg
    - assets/img/basquetbol.jpg
    - assets/img/beisbol.jpg
    - assets/img/biblioteca.jpg
    - assets/img/cajero.jpg
    - assets/img/casileros.jpg
    - assets/img/computadora.jpg
    - assets/img/conferencia.jpg
    - assets/img/consejo.jpg
    - assets/img/cuatro.jpg
    - assets/img/dos.jpeg
    - assets/img/escom_background.jpg
    - assets/img/escom_logo.png
    - assets/img/estacionamiento.jpg
    - assets/img/explanada.jpg
    - assets/img/expo1.jpg
    - assets/img/expo2.jpg
    - assets/img/fachada.jpg
    - assets/img/foto.jpg
    - assets/img/futbol.jpg
    - assets/img/arcoiris.jpg
    - assets/img/genesis.jpg
    - assets/img/ia.png
    - assets/img/ia1.jpg
    - assets/img/ia3.jpg
    - assets/img/icpc.jpg
    - assets/img/inauguranIA.jpg
    - assets/img/infra.jpg
    - assets/img/isa.jpg
    - assets/img/isc.png
    - assets/img/lab.jpg
    - assets/img/labComputo.jpg
    - assets/img/lcd.jpg
    - assets/img/letras.jpg
    - assets/img/miacd.jpg
    - assets/img/motos.jpg
    - assets/img/mscm.jpg
    - assets/img/mural.jpg
    - assets/img/musica.jpg
    - assets/img/navidad.jpg
    - assets/img/pingpong.jpg
    - assets/img/pintura.jpg
    - assets/img/primera.jpg
    - assets/img/ranking.PNG
    - assets/img/rebelion.jpg
    - assets/img/rebelion1.jpg
    - assets/img/rebelion2.jpg
    - assets/img/rector.jpg
    - assets/img/robotica.jpg
    - assets/img/taekwondo.PNG
    - assets/img/teatro.jpg
    - assets/img/tiburon.jpg
    - assets/img/titulado.jpg
    - assets/img/tres.jpeg
    - assets/img/tuna.jpg
    - assets/img/uno.jpeg
    - assets/img/voleibol.jpg
    - assets/img/facebook.png
    - assets/img/x.png
    - assets/img/instagram.png
    - assets/img/youtube.png
    - assets/img/fondo.jpg
    - assets/data/alumnos.json
    - assets/data/profesores.json
    - assets/data/horarios_profesores.json
    - assets/docs/mapaCurricularISC.pdf
    - assets/docs/mapaCurricularIIA.pdf
    - assets/docs/mapaCurricularLCD.pdf
    - assets/docs/mapaCurricularISA.pdf
    - assets/docs/mapaCurricularMSCM.pdf
    - assets/docs/optativasIA.pdf
    - assets/docs/optativasISC.pdf
    - assets/docs/optativasLCD.pdf

